apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: roboshop
  labels: 
    app: rabbitmq
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
      tier: app
  template:
    metadata:
      labels:
        app: rabbitmq
        tier: app
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    app: rabbitmq
    tier: app
  ports:
  - name: rabbitmq-port
    protocol: TCP
    port: 5672 # Service Port
    targetPort: 5672 # container-port
