apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    app: mongodb
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: db
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
    spec:
      containers:
      - image: gspvsr/mongodb:1.0.0
        name: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
spec:
  selector:
    app: mongodb
    tier: db
  ports:
  - name: mongodb-port
    protocol: TCP
    port: 27017 # This prot belongs to service
    targetPort: 27017 # this port belongs to container