apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels: 
    app: user
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      tier: app
  template:
    metadata:
      labels:
        app: user
        tier: app
    spec:
      containers:
      - name: user
        image: gspvsr/user:1.0.0
        envFrom:
        - configMapRef:
            name: user
        # Optional but recommended probes
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    app: user
    tier: app
  ports:
  - name: http-port
    protocol: TCP
    port: 8080 # Service Port
    targetPort: 8080 # Container Port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/user"
  MONGO_HOST: "mongodb"
  REDIS_HOST: "redis"
