apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  labels: 
    app: user
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: user
        tier: app
        project: roboshop
    spec:
      containers:
      - name: user
        image: gspvsr/user:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    app: user
    tier: app
    project: roboshop
  ports:
  - name: catalogue-port
    protocol: TCP
    port: 8080 # Service Port
    targetPort: 8080 # container-port
