apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  labels: 
    app: redis
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: redis
        tier: app
        project: roboshop
    spec:
      containers:
      - name: redis
        image: redis
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    app: redis
    tier: app
    project: roboshop
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379 # Service Port
    targetPort: 6379 # container-port
